#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_EMACS
#define UNICODE_TYPE_DELAY 8

#define TAP_CODE_DELAY 8

#define EE_HANDS

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define RGBLIGHT_SPLIT
#define RGBLIGHT_LAYERS


#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
